### ISSUE TITLE
Error resolving user pathname with accentuated letters

### ISSUE THREAD

**Issue by Ylangz** [Colossal1/plugin.video.xxx-o-dus#27]
I'm running this add-on on several machine and have an issue on Windows 7 where I keep getting "XXX-O-DUS error. Check the log for more information".

It looks like there is an issue with the pathname handling when it include accentuated letters
- The add-on data are located in : C:\Users\Jérôme\AppData\Roaming\Kodi\
- It keep creating an empty folder : C:\Users\JÃ©rÃ´me\AppData\Roaming\Kodi\

You will notice the diference in the username spelling ... Here the relevent log part : 

`22:21:54.620 T:5316   ERROR: EXCEPTION Thrown (PythonToCppException) :
	-->Python callback/script returned the following error<--
	- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
	Error Type: <type 'exceptions.WindowsError'>
        Error Contents: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:\\Users\\J\xc3\xa9r\xc3\xb4me\\AppData\\Roaming\\Kodi\\addons\\script.module.urlresolver.xxx\\resources\\plugins\\*.*')
	Traceback (most recent call last):
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\default.py", line 18, in <module>
		sys.exit(main())
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\default.py", line 13, in main
		utils.url_dispatcher.dispatch(mode, queries)
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\script.module.echo\lib\url_dispatcher.py", line 93, in dispatch
		self.func_registry[mode](*args, **kwargs)
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\plugin.video.xxx-o-dus\resources\lib\modules\player.py", line 38, in resolve_url
		if urlresolver.HostedMediaFile(url).valid_url():
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\hmf.py", line 85, in __init__
		self.__resolvers = self.__get_resolvers(include_disabled, include_universal)
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\hmf.py", line 101, in __get_resolvers
		include_external=True, include_disabled=include_disabled, order_matters=True)
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\__init__.py", line 72, in relevant_resolvers
		load_external_plugins()
	File "C:\Users\J�r�me\AppData\Roaming\Kodi\addons\script.module.urlresolver\lib\urlresolver\__init__.py", line 63, in load_external_plugins
		for filename in os.listdir(d):
	WindowsError: (3, 'Le chemin d\x92acc\xe8s sp\xe9cifi\xe9 est introuvable', 'C:\\Users\\J\xc3\xa9r\xc3\xb4me\\AppData\\Roaming\\Kodi\\addons\\script.module.urlresolver.xxx\\resources\\plugins\\*.*')
	-->End of Python script error report<--
`

**Comment by Colossal1** [comment]
@Ylangz Seeing as this error is happening through the 

xbmc.translatepath function here:

http://mirrors.kodi.tv/docs/python-docs/13.0-gotham/xbmc.html#-translatePath

I suggest you raise the issue on the XBMC git as it is their function that is failing to translate characters properly.

Thanks.
